######################################################################
# Automatically generated by qmake (2.01a) sab nov 9 02:45:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += key.hpp mainWindow.hpp note.hpp
SOURCES += key.cpp main.cpp mainWindow.cpp note.cpp
