######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 20 14:42:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += audiooutputstreamer.hpp key.hpp keyboard.hpp mainWindow.hpp
SOURCES += audiooutputstreamer.cpp key.cpp keyboard.cpp main.cpp mainWindow.cpp
